# Generated by Django 5.0.14 on 2026-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Ex: /ancienne-url (sans le domaine)', max_length=500, unique=True, verbose_name='Ancien chemin')),
                ('new_path', models.CharField(help_text='Ex: /nouvelle-url ou https://externe.com', max_length=500, verbose_name='Nouveau chemin')),
                ('redirect_type', models.CharField(choices=[('301', '301 — Permanent (SEO)'), ('302', '302 — Temporaire')], default='301', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de visites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redirection',
                'verbose_name_plural': 'Redirections',
                'ordering': ['-created_at'],
            },
        ),
    ]
