# Generated by Django 5.0.14 on 2026-10-01 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NAWA Design System', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Un seul design system peut être actif à la fois.')),
                ('color_primary', models.CharField(default='#C1652F', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Couleur primaire')),
                ('color_secondary', models.CharField(default='#2F4A3C', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Couleur secondaire')),
                ('color_background', models.CharField(default='#F7F0E4', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Fond de page')),
                ('color_surface', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Surface (cartes)')),
                ('color_text', models.CharField(default='#221B15', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Texte principal')),
                ('color_text_muted', models.CharField(default='#6B6259', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Texte secondaire')),
                ('color_accent', models.CharField(default='#D4A843', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name="Couleur d'accent (or)")),
                ('color_error', models.CharField(default='#DC2626', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Erreur')),
                ('color_success', models.CharField(default='#16A34A', max_length=7, validators=[django.core.validators.RegexValidator(message='Entrez une couleur hexadécimale valide (ex: #C1652F).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Succès')),
                ('font_heading', models.CharField(default='Fraunces', help_text='Nom de la police Google Fonts (ex: Fraunces).', max_length=100, verbose_name='Police des titres')),
                ('font_body', models.CharField(default='Sora', help_text='Nom de la police Google Fonts (ex: Sora, Inter).', max_length=100, verbose_name='Police du corps')),
                ('font_size_base', models.CharField(default='16px', max_length=20, verbose_name='Taille de base')),
                ('font_size_h1', models.CharField(default='3.5rem', max_length=20, verbose_name='Taille H1')),
                ('font_size_h2', models.CharField(default='2.5rem', max_length=20, verbose_name='Taille H2')),
                ('font_size_h3', models.CharField(default='1.75rem', max_length=20, verbose_name='Taille H3')),
                ('line_height', models.CharField(default='1.6', max_length=10, verbose_name='Hauteur de ligne')),
                ('border_radius', models.CharField(default='16px', max_length=20, verbose_name='Rayon des bordures')),
                ('button_radius', models.CharField(default='999px', max_length=20, verbose_name='Rayon des boutons')),
                ('card_radius', models.CharField(default='16px', max_length=20, verbose_name='Rayon des cartes')),
                ('shadow_sm', models.CharField(default='0 1px 2px rgba(0,0,0,0.05)', max_length=100, verbose_name='Ombre petite')),
                ('shadow_md', models.CharField(default='0 4px 12px rgba(0,0,0,0.10)', max_length=100, verbose_name='Ombre moyenne')),
                ('shadow_lg', models.CharField(default='0 10px 30px rgba(0,0,0,0.15)', max_length=100, verbose_name='Ombre grande')),
                ('custom_css', models.TextField(blank=True, help_text='CSS additionnel injecté dans le <head> (avancé).', verbose_name='CSS personnalisé')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Design System',
                'verbose_name_plural': 'Design System',
            },
        ),
    ]
