# Generated by Django 5.0.14 on 2026-09-30 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency_days', models.PositiveSmallIntegerField(choices=[(30, 'Tous les 30 jours'), (45, 'Tous les 45 jours'), (60, 'Tous les 60 jours'), (90, 'Tous les 90 jours')], default=30)),
                ('discount_percent', models.PositiveSmallIntegerField(default=20)),
                ('active', models.BooleanField(default=True)),
                ('next_delivery_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='catalog.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
