# Generated by Django 5.0.14 on 2026-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.TextField(help_text='Code HTML/JS à injecter (balises <script> incluses).', verbose_name='Code')),
                ('location', models.CharField(choices=[('head', 'Dans le <head>'), ('body_start', 'Début du <body>'), ('body_end', 'Fin du <body>')], default='head', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('require_consent', models.BooleanField(default=False, help_text="Ne charger qu'après acceptation des cookies.", verbose_name='Nécessite consentement (RGPD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Script tiers',
                'verbose_name_plural': 'Scripts tiers',
                'ordering': ['name'],
            },
        ),
    ]
