# Generated by Django 5.0.14 on 2026-09-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('connector_type', models.CharField(choices=[('crm', 'CRM'), ('erp', 'ERP'), ('emailing', 'Emailing')], max_length=10)),
                ('base_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integration.integrationconnector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
