# Generated by Django 5.0.14 on 2026-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant technique (ex: order_confirmation, welcome).', max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('body_text', models.TextField(blank=True, help_text='Version plain-text (recommandée pour la délivrabilité).', verbose_name='Version texte')),
                ('body_html', models.TextField(blank=True, help_text='Version HTML avec mise en forme.', verbose_name='Version HTML')),
                ('from_email', models.EmailField(blank=True, default='', help_text='Vide = utilise DEFAULT_FROM_EMAIL.', max_length=254, verbose_name='Email expéditeur')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Ex: ["user_name", "order_id", "total"]', verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'emails",
                'ordering': ['code'],
            },
        ),
    ]
