# Generated by Django 5.0.14 on 2026-10-01 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du formulaire')),
                ('slug', models.SlugField(help_text='Identifiant technique (ex: contact, newsletter).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('success_message', models.TextField(default='Merci, votre message a bien été envoyé.', verbose_name='Message de succès')),
                ('redirect_url', models.CharField(blank=True, help_text="Si vide, le message de succès s'affiche sur place.", max_length=500, verbose_name='URL de redirection')),
                ('email_notification', models.EmailField(blank=True, help_text='Adresse qui reçoit un email à chaque soumission.', max_length=254, verbose_name='Email de notification')),
                ('captcha_enabled', models.BooleanField(default=False, verbose_name='Activer le CAPTCHA')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Données soumises (clé/valeur)')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé'), ('spam', 'Spam')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formdefinition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('field_key', models.SlugField(help_text='Identifiant du champ dans le formulaire (ex: nom, email).', max_length=100, verbose_name='Clé technique')),
                ('field_type', models.CharField(choices=[('text', 'Texte court'), ('textarea', 'Texte long'), ('email', 'Email'), ('phone', 'Téléphone'), ('number', 'Nombre'), ('date', 'Date'), ('select', 'Liste déroulante'), ('radio', 'Boutons radio'), ('checkbox', 'Case à cocher'), ('file', 'Fichier')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name="Texte d'aide")),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list, help_text='Pour les listes/radios : [{"value": "a", "label": "Option A"}, ...]')),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formdefinition')),
            ],
            options={
                'verbose_name': 'Champ de formulaire',
                'verbose_name_plural': 'Champs de formulaire',
                'ordering': ['order'],
                'unique_together': {('form', 'field_key')},
            },
        ),
    ]
