# Generated by Django 5.0.14 on 2026-10-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du menu')),
                ('slug', models.SlugField(help_text='Identifiant technique (ex: header-main).', max_length=100, unique=True)),
                ('location', models.CharField(choices=[('header', 'En-tête'), ('footer', 'Pied de page'), ('mobile', 'Menu mobile'), ('sidebar', 'Barre latérale')], default='header', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['location', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('url', models.CharField(blank=True, help_text='Lien relatif (/boutique) ou absolu (https://...).', max_length=500, verbose_name='URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='navigation/icons/', verbose_name='Icône')),
                ('target', models.CharField(choices=[('_self', 'Même onglet'), ('_blank', 'Nouvel onglet')], default='_self', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('badge_text', models.CharField(blank=True, max_length=20, verbose_name='Badge (ex: Nouveau)')),
                ('badge_color', models.CharField(blank=True, default='#C1652F', max_length=7, verbose_name='Couleur du badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem')),
            ],
            options={
                'verbose_name': 'Élément de menu',
                'verbose_name_plural': 'Éléments de menu',
                'ordering': ['order', 'label'],
            },
        ),
    ]
