# Generated by Django 5.0.14 on 2026-10-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='visibility',
            field=models.CharField(choices=[('all', 'Tout le monde'), ('anonymous', 'Visiteurs non connectés'), ('authenticated', 'Utilisateurs connectés'), ('staff', 'Staff (gestionnaires)'), ('superuser', 'Superutilisateurs uniquement')], default='all', help_text='Qui peut voir cet élément de menu ?', max_length=20, verbose_name='Visible par'),
        ),
    ]
