# Generated by Django 5.0.14 on 2026-10-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('meta_title', models.CharField(blank=True, help_text='60-70 caractères recommandés.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='150-160 caractères recommandés.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Séparés par des virgules.', max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('og_type', models.CharField(choices=[('website', 'Site web'), ('article', 'Article'), ('product', 'Produit'), ('profile', 'Profil'), ('video.other', 'Vidéo')], default='website', max_length=20)),
                ('twitter_card', models.CharField(choices=[('summary', 'Résumé'), ('summary_large_image', 'Résumé + grande image')], default='summary_large_image', max_length=20)),
                ('canonical_url', models.URLField(blank=True, help_text='URL canonique (laisser vide pour auto).')),
                ('robots', models.CharField(choices=[('index,follow', 'Indexer + Suivre (par défaut)'), ('index,nofollow', 'Indexer + Ne pas suivre'), ('noindex,follow', 'Ne pas indexer + Suivre'), ('noindex,nofollow', 'Ne pas indexer + Ne pas suivre')], default='index,follow', max_length=30)),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Format JSON-LD (schema.org).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Métadonnée SEO',
                'verbose_name_plural': 'Métadonnées SEO',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
