# Generated by Django 5.0.14 on 2026-09-30 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('context', models.CharField(choices=[('product', 'Produit'), ('post', 'Article de blog'), ('user', 'Utilisateur'), ('order', 'Commande'), ('site', 'Site')], max_length=10)),
            ],
            options={
                'ordering': ['context', 'source'],
            },
        ),
        migrations.CreateModel(
            name='GlobalDesignSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='NAWA Design System', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('global_colors', models.JSONField(default=dict)),
                ('global_typography', models.JSONField(default=dict)),
                ('global_components', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('template_type', models.CharField(choices=[('home', 'Accueil'), ('header', 'Header (global)'), ('footer', 'Footer (global)'), ('single_product', 'Fiche produit'), ('product_archive', 'Liste/grille produits'), ('cart', 'Panier'), ('checkout', 'Tunnel de commande'), ('my_account', 'Mon compte'), ('blog_list', "Liste d'articles"), ('blog_single', 'Article de blog'), ('page_generic', 'Page générique'), ('404', 'Page 404')], max_length=20)),
                ('display_conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='cms/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('heading', 'Titre'), ('text', 'Texte'), ('image', 'Image'), ('video', 'Vidéo'), ('button', 'Bouton'), ('section', 'Section'), ('columns', 'Colonnes'), ('product_single', 'Widget produit (fiche)'), ('product_grid', 'Grille de produits'), ('blog_list', "Liste d'articles"), ('faq', 'FAQ'), ('form', 'Formulaire'), ('menu_cart', 'Mini-panier'), ('cart_widget', 'Widget panier complet'), ('checkout_widget', 'Widget tunnel de commande'), ('my_account_widget', 'Widget mon compte')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('dynamic_content', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.pagetemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('templates', models.ManyToManyField(blank=True, related_name='site_kits', to='cms.pagetemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
