# Generated by Django 5.0.14 on 2026-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldesignsystem',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='cms/favicons/', verbose_name='Favicon du site'),
        ),
        migrations.AddField(
            model_name='globaldesignsystem',
            name='icon_cart',
            field=models.ImageField(blank=True, null=True, upload_to='cms/icons/', verbose_name='Icône du panier'),
        ),
        migrations.AddField(
            model_name='globaldesignsystem',
            name='icon_search',
            field=models.ImageField(blank=True, null=True, upload_to='cms/icons/', verbose_name='Icône de recherche'),
        ),
        migrations.AddField(
            model_name='globaldesignsystem',
            name='icon_user',
            field=models.ImageField(blank=True, null=True, upload_to='cms/icons/', verbose_name='Icône utilisateur'),
        ),
        migrations.AddField(
            model_name='globaldesignsystem',
            name='logo_principal',
            field=models.ImageField(blank=True, null=True, upload_to='cms/logos/', verbose_name='Logo principal'),
        ),
    ]
