# Generated by Django 5.0.14 on 2026-10-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_globaldesignsystem_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cms/sections/')),
                ('structure', models.JSONField(default=dict, help_text='Arbre complet de widgets sérialisé en JSON.')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Section réutilisable',
                'verbose_name_plural': 'Sections réutilisables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('section', 'Section'), ('column', 'Colonne'), ('container', 'Conteneur'), ('heading', 'Titre'), ('text', 'Texte'), ('image', 'Image'), ('button', 'Bouton'), ('divider', 'Séparateur'), ('spacer', 'Espace'), ('icon', 'Icône'), ('icon_box', 'Bloc icône'), ('html', 'Code HTML'), ('tabs', 'Onglets'), ('accordion', 'Accordéon'), ('toggle', 'Boîte à bascule'), ('table_of_contents', 'Table des matières'), ('progress', 'Barre de progression'), ('counter', 'Compteur animé'), ('countdown', 'Compte à rebours'), ('gallery', 'Galerie'), ('carousel', 'Carrousel'), ('carousel_loop', 'Carrousel en boucle'), ('carousel_media', 'Carrousel média'), ('carousel_nested', 'Carrousel imbriqué'), ('slides', 'Diapositives'), ('video', 'Vidéo'), ('video_playlist', 'Liste de lecture vidéo'), ('lottie', 'Lottie'), ('hotspot', "Point d'accès (Hotspot)"), ('cta', "Appel à l'action"), ('testimonial', 'Témoignage'), ('testimonial_carousel', 'Témoignages en carrousel'), ('review', 'Avis'), ('pricing_table', 'Tableau des prix'), ('pricing_list', 'Liste des prix'), ('progress_review', 'Suivi des avis'), ('social_share', 'Boutons de partage'), ('facebook_page', 'Page Facebook'), ('facebook_button', 'Bouton Facebook'), ('facebook_embed', 'Intégration Facebook'), ('facebook_comments', 'Commentaires Facebook'), ('paypal_button', 'Bouton PayPal'), ('stripe_button', 'Bouton Stripe'), ('portfolio', 'Portfolio'), ('form', 'Formulaire'), ('login', 'Connexion'), ('menu', 'Menu de navigation'), ('mega_menu', 'Méga menu'), ('off_canvas', 'Hors cadre'), ('archive_posts', 'Archive Posts'), ('archive_title', 'Archive Title'), ('breadcrumbs', 'Breadcrumbs'), ('post_comments', 'Post Comments'), ('post_content', 'Post Content'), ('post_excerpt', 'Post Excerpt'), ('post_info', 'Post Info'), ('post_navigation', 'Post Navigation'), ('post_title', 'Post Title'), ('site_logo', 'Site Logo'), ('site_title', 'Site Title'), ('sitelink_search', 'Sitelink Search Box'), ('loop_grid', 'Loop Grid'), ('loop_carousel', 'Loop Carousel'), ('taxonomy', 'Taxonomy'), ('author_box', 'Author Box'), ('post_portfolio', 'Post/Portfolio'), ('products', 'Products'), ('wc_breadcrumbs', 'WooCommerce Breadcrumbs'), ('product_title', 'Product Title'), ('product_images', 'Product Images'), ('product_price', 'Product Price'), ('add_to_cart', 'Add to Cart'), ('product_rating', 'Product Rating'), ('product_stock', 'Product Stock'), ('product_meta', 'Product Meta'), ('short_description', 'Short Description'), ('product_content', 'Product Content'), ('product_data_tabs', 'Product Data Tabs'), ('upsells', 'Upsells'), ('related_products', 'Related Products'), ('product_categories', 'Product Categories'), ('menu_cart', 'Menu Cart'), ('cart', 'Cart'), ('checkout', 'Checkout'), ('my_account', 'My Account'), ('purchase_summary', 'Purchase Summary')], max_length=40)),
                ('name', models.CharField(blank=True, help_text="Nom custom dans l'éditeur", max_length=100)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Contenu du widget. Ex: {"text": "Bonjour", "level": "h1"}')),
                ('style', models.JSONField(blank=True, default=dict, help_text='Style responsive. Ex: {"padding": "80px 0", "background": "#fff"}')),
                ('custom_css', models.TextField(blank=True)),
                ('custom_id', models.CharField(blank=True, max_length=100)),
                ('custom_classes', models.CharField(blank=True, max_length=255)),
                ('animation', models.CharField(blank=True, help_text='fade, slide, zoom...', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='cms.pagetemplate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.widget')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['order'],
            },
        ),
    ]
