# Generated by Django 5.0.14 on 2026-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
                ('link', models.URLField(blank=True, verbose_name='Lien')),
                ('link_label', models.CharField(blank=True, help_text="Ex: 'En savoir plus', 'Profiter de l'offre'", max_length=100, verbose_name='Texte du lien')),
                ('background_color', models.CharField(default='#C1652F', max_length=7, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Couleur du texte')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='announcements/icons/', verbose_name='Icône (optionnelle)')),
                ('position', models.CharField(choices=[('top_bar', 'Bandeau supérieur'), ('bottom', 'Bandeau inférieur'), ('popup', 'Popup central'), ('floating', 'Bulle flottante')], default='top_bar', max_length=20, verbose_name='Position')),
                ('target_audience', models.CharField(choices=[('all', 'Tout le monde'), ('anonymous', 'Visiteurs non connectés'), ('authenticated', 'Utilisateurs connectés')], default='all', max_length=20, verbose_name='Audience cible')),
                ('target_pages', models.CharField(blank=True, help_text='Vide = toutes les pages. Sinon, URLs séparées par des virgules (ex: /, /boutique/cosmetiques).', max_length=500, verbose_name='Pages ciblées')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Début (optionnel)')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin (optionnel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activée')),
                ('order', models.PositiveIntegerField(default=0, help_text='Plus petit = affiché en premier.', verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
