# Generated by Django 5.0.14 on 2026-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant technique (ex: wishlist, reviews).', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom affiché')),
                ('description', models.TextField(blank=True, help_text='Description de ce que fait ce flag.')),
                ('is_enabled', models.BooleanField(default=False, help_text='Activer la fonctionnalité dans le frontend.', verbose_name='Activé')),
                ('target_audience', models.CharField(choices=[('all', 'Tout le monde'), ('authenticated', 'Utilisateurs connectés'), ('staff', 'Staff uniquement'), ('beta', 'Bêta-testeurs')], default='all', help_text="À qui s'applique ce flag ?", max_length=20, verbose_name='Audience cible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['code'],
            },
        ),
    ]
