# Generated by Django 5.0.14 on 2026-10-01 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='#6B6259', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Étiquette média',
                'verbose_name_plural': 'Étiquettes média',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media-library/%Y/%m/', verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF'), ('document', 'Document'), ('other', 'Autre')], default='image', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Taille en octets')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('alt_text', models.CharField(blank=True, help_text="Important pour le SEO et l'accessibilité.", max_length=255, verbose_name='Texte alternatif')),
                ('caption', models.TextField(blank=True, verbose_name='Légende')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='media_library.mediatag')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médiathèque',
                'ordering': ['-created_at'],
            },
        ),
    ]
