# Generated by Django 5.0.14 on 2026-10-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identifiant unique. Convention : module.section.cle (ex: cart.empty.message)', max_length=200, unique=True)),
                ('values', models.JSONField(default=dict, help_text='Format : {"fr": "...", "en": "..."}')),
                ('context', models.CharField(blank=True, help_text='Où ce texte apparaît (ex: Panier, Header).', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Notes pour les traducteurs (contexte, ton, variables).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clé de traduction',
                'verbose_name_plural': 'Clés de traduction',
                'ordering': ['key'],
            },
        ),
    ]
